import '../flash_card/model/flashcard.model.dart';

final ENGLISH_FLASHCARD = [
  FlashCardModel(frontText: "A", backText: "Um, uma"),
  FlashCardModel(frontText: "An", backText: "Um, uma"),
  FlashCardModel(frontText: "The", backText: "O, a, os, as"),
  FlashCardModel(frontText: "All", backText: "Todo, Tudo"),
  FlashCardModel(frontText: "Anyone", backText: "Qualquer Um"),
  FlashCardModel(frontText: "Anything", backText: "Nada"),
  FlashCardModel(frontText: "Both", backText: "Ambos"),
  FlashCardModel(frontText: "Each", backText: "Cada"),
  FlashCardModel(frontText: "Everyone", backText: "Todos"),
  FlashCardModel(frontText: "Everything", backText: "Tudo"),
  FlashCardModel(frontText: "He", backText: "Ele"),
  FlashCardModel(frontText: "Himself", backText: "Ele Mesmo"),
  FlashCardModel(frontText: "I", backText: "Eu"),
  FlashCardModel(frontText: "It", backText: "Isto"),
  FlashCardModel(frontText: "My", backText: "Meu, minha"),
  FlashCardModel(frontText: "Myself", backText: "Eu Mesmo"),
  FlashCardModel(frontText: "Nothing", backText: "Nada"),
  FlashCardModel(frontText: "She", backText: "Ela"),
  FlashCardModel(frontText: "Some", backText: "Algum"),
  FlashCardModel(frontText: "Someone", backText: "Alguém"),
  FlashCardModel(frontText: "Something", backText: "Algo"),
  FlashCardModel(frontText: "Them", backText: "Eles, Elas"),
  FlashCardModel(frontText: "They", backText: "Eles, Elas"),
  FlashCardModel(frontText: "This", backText: "Este, esta"),
  FlashCardModel(frontText: "We", backText: "Nós"),
  FlashCardModel(frontText: "What", backText: "O Que"),
  FlashCardModel(frontText: "Which", backText: "Qual"),
  FlashCardModel(frontText: "Who", backText: "Quem"),
  FlashCardModel(frontText: "You", backText: "Você"),
  FlashCardModel(frontText: "Your", backText: "Seu, sua"),
  FlashCardModel(frontText: "About", backText: "Sobre"),
  FlashCardModel(frontText: "After", backText: "Depois"),
  FlashCardModel(frontText: "Against", backText: "Contra"),
  FlashCardModel(frontText: "Among", backText: "Entre"),
  FlashCardModel(frontText: "Around", backText: "Em torno"),
  FlashCardModel(frontText: "At", backText: "Em"),
  FlashCardModel(frontText: "Before", backText: "Antes"),
  FlashCardModel(frontText: "Between", backText: "Entre"),
  FlashCardModel(frontText: "By", backText: "Por, Em"),
  FlashCardModel(frontText: "During", backText: "Durante"),
  FlashCardModel(frontText: "For", backText: "Para"),
  FlashCardModel(frontText: "From", backText: "De"),
  FlashCardModel(frontText: "In", backText: "Em"),
  FlashCardModel(frontText: "Into", backText: "Dentro"),
  FlashCardModel(frontText: "Of", backText: "De"),
  FlashCardModel(frontText: "On", backText: "Sobre"),
  FlashCardModel(frontText: "Through", backText: "Através"),
  FlashCardModel(frontText: "To", backText: "Para"),
  FlashCardModel(frontText: "Under", backText: "Embaixo"),
  FlashCardModel(frontText: "With", backText: "Com"),
  FlashCardModel(frontText: "Without", backText: "Sem"),
  FlashCardModel(frontText: "Although", backText: "Apesar"),
  FlashCardModel(frontText: "And", backText: "E"),
  FlashCardModel(frontText: "As", backText: "Como"),
  FlashCardModel(frontText: "Because", backText: "Porque"),
  FlashCardModel(frontText: "But", backText: "Mas"),
  FlashCardModel(frontText: "Except", backText: "Exceto"),
  FlashCardModel(frontText: "If", backText: "Se"),
  FlashCardModel(frontText: "Like", backText: "Como"),
  FlashCardModel(frontText: "Nor", backText: "Nem"),
  FlashCardModel(frontText: "Once", backText: "Uma Vez"),
  FlashCardModel(frontText: "Or", backText: "Ou"),
  FlashCardModel(frontText: "Since", backText: "Desde"),
  FlashCardModel(frontText: "So", backText: "Assim, Tão, Então"),
  FlashCardModel(frontText: "Than", backText: "Do Que"),
  FlashCardModel(frontText: "That", backText: "Que"),
  FlashCardModel(frontText: "Though", backText: "No Entanto"),
  FlashCardModel(frontText: "Unless", backText: "A Não Ser Que"),
  FlashCardModel(frontText: "Until", backText: "Até"),
  FlashCardModel(frontText: "Where", backText: "Onde"),
  FlashCardModel(frontText: "Whether", backText: "Se"),
  FlashCardModel(frontText: "While", backText: "Enquanto"),
  FlashCardModel(frontText: "Yet", backText: "Ainda"),
  FlashCardModel(frontText: "Are", backText: "São, Estão"),
  FlashCardModel(frontText: "Ask", backText: "Perguntar"),
  FlashCardModel(frontText: "Be", backText: "Ser, Estar"),
  FlashCardModel(frontText: "Been", backText: "Sido, Estado"),
  FlashCardModel(frontText: "Call", backText: "Chamar, Ligar"),
  FlashCardModel(frontText: "Can", backText: "Pode"),
  FlashCardModel(frontText: "Come", backText: "Vir"),
  FlashCardModel(frontText: "Could", backText: "Poderia"),
  FlashCardModel(frontText: "Cry", backText: "Chorar"),
  FlashCardModel(frontText: "Did", backText: "Fez"),
  FlashCardModel(frontText: "Do", backText: "Fazer"),
  FlashCardModel(frontText: "Drink", backText: "Beber"),
  FlashCardModel(frontText: "Eat", backText: "Comer"),
  FlashCardModel(frontText: "Feel", backText: "Sentir"),
  FlashCardModel(frontText: "Find", backText: "Encontrar"),
  FlashCardModel(frontText: "Get", backText: "Obter"),
  FlashCardModel(frontText: "Give", backText: "Dar"),
  FlashCardModel(frontText: "Go", backText: "Ir"),
  FlashCardModel(frontText: "Had", backText: "Tinha"),
  FlashCardModel(frontText: "Have", backText: "Ter"),
]..shuffle();
